// NODE MODULES..................................
/*Se encuentra todos los modulos necesarios para el correcto funcionamiento de la aplicación*/

// PUBLIC........................................
/* Contenido de un aplicación web progresiva, lo mas importante es el index.html*/

// GIT IGNORE....................................
// versiones

//PACKAGE.JSON....................................
// Dependencias
// Scripts

// README.........................................
//Descripción del proyecto
